name: My GitHub Actions Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'github_actions_workflow/**'
jobs:
 testing_github:
  runs-on: ubuntu-latest
  steps:
    - name: Hello
      run: echo "Hello, GitHub Actions!"
    - name: Display repo name
      run: echo "this workflow is running in ${{ github.repository }}"